---
- hosts: all
  become: yes
  tasks:
    - name: Install Unzip
      apt:
        pkg: unzip
        update_cache: yes
    - name: Download Consul
      get_url:
        url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
        dest: "/tmp/consul-{{ consul_version }}_linux_amd64.zip"
    - name: Unzip Consul
      unarchive:
        src: "/tmp/consul-{{ consul_version }}_linux_amd64.zip"
        dest: /usr/local/bin
        copy: no
        group: root
        owner: root
        mode: 0755
    - name: Start server
      command: /usr/local/bin/consul agent -dev
