language: go

dist: jammy

go:
  - 1.21.0

env:
  matrix:
    - CONSUL_VERSION: 1.16.1

install:
  # install go dependencies
  - go get

script:
  # install and start consul
  - wget https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
  - sudo unzip -d /usr/local/bin consul_${CONSUL_VERSION}_linux_amd64.zip
  - sudo chmod +x /usr/local/bin/consul
  - consul agent -dev &
  # build, configure, start consul-alerts
  - make build
  - curl -XPUT -d @provision/fixtures/notif-profile.json 127.0.0.1:8500/v1/kv/consul-alerts/config/notif-profiles/log
  - curl -XPUT -d @provision/fixtures/notif-selection.json 127.0.0.1:8500/v1/kv/consul-alerts/config/notif-selection/hosts
  - curl -XPUT -d 1 127.0.0.1:8500/v1/kv/consul-alerts/config/checks/change-threshold
  - build/bin/Linux-x86_64/latest/consul-alerts start --watch-events --watch-checks --consul-addr=127.0.0.1:8500 &
  # install and start nomad
  - wget https://releases.hashicorp.com/nomad/1.6.1/nomad_1.6.1_linux_amd64.zip
  - sudo unzip -d /usr/local/bin nomad_1.6.1_linux_amd64.zip
  - sudo chmod +x /usr/local/bin/nomad
  - nomad agent -dev -consul-address=127.0.0.1:8500 &
  - sleep 15 # give nomad some time to start
  # drop packets between nomad and consul to make the nomad service unhealthy
  - sudo iptables -A INPUT -s 127.0.0.1 -p tcp --dport 4646 -j DROP
  - sleep 45 # give consul-alerts some time to report
  # make sure that consul-alerts reported that the service is failing
  - cat /tmp/consul-notifications.log | grep "Service=nomad-client, Check=Nomad Client HTTP Check, Status=critical"
  # restore the connection between nomad and consul
  - sudo iptables -D INPUT -s 127.0.0.1 -p tcp --dport 4646 -j DROP
  - sleep 45
  # make sure that consul-alerts reported that the service is healthy
  - cat /tmp/consul-notifications.log | grep "Service=nomad-client, Check=Nomad Client HTTP Check, Status=passing"
